export { default as Header} from './header/Header'
export {default as Footer} from './footer/Footer'
export {default as Home } from './home/Home'
export {default as Hero  } from './hero/Hero'
export {default as How} from './how/How'
export {default as Faq} from './faq/Faq'
export {default as Contact } from './contact/Contact'
export {default as Browse} from './browse/Browse'
export {default as Topic } from './topic/Topic'
export {default as Contact_form} from './contact_form/Contact_form'
export {default as Pages} from './pages/Pages'
export {default as Webdesign} from './webDesign/Webdesign'
