export {default as Facebook } from './icon-facebook.svg'
export {default as Twitter } from './icon-twitter.svg'
export {default as Pinterest} from './icon-pinterest.svg'
export {default as Instagram} from './icon-instagram.svg'
export {default as Hamburger} from './icon-hamburger.svg'
export {default as Close } from './icon-close.svg'
export {default as Hero__img} from './hero-img.jpg'
export {default as Hero__img2} from './hero-img2.png'
export {default as Browse1} from './browse1.png'
export {default as Browse2} from './browse2.png'
export {default as Browse3} from './browse3.png'
export {default as Browse4} from './browse4.png'
export {default as Browse5} from './browse5.png'
export {default as Browse6} from './browse6.png'
export {default as Browse7} from './browse7.png'
export {default as Browse8} from './browse8.png'
export {default as Browse9} from './browse9.png'
export {default as Browse10} from './browse10.png'
export {default as Browse11} from './browse11.png'
export {default as Faq_graphics} from './faq_graphic.jpg'
export {default as Webimg} from './web_img.jpg'
export {default as News} from './news.jpg'
export {default as Topic1} from './topic1.png'